using System.Collections;
using System.Diagnostics;
using Grpc.Core;
using Grpc.Core.Interceptors;
using Microsoft.Extensions.Logging;

namespace Taakht.Platform;

/// <summary>
/// Ambient request id (gRPC metadata <see cref="Header"/>, generated by Envoy for every REST call). The server
/// interceptor sets it for the call, outgoing gRPC calls forward it, <see cref="Outbox"/> stores it in the envelope and
/// the event consumer restores it, so one id spans synchronous and asynchronous hops.
/// </summary>
public static class RequestContext
{
    public const string Header = "x-request-id";

    /// <summary>Longest accepted id; longer or non-printable values are replaced by a fresh id.</summary>
    public const int MaxLength = 128;

    private static readonly AsyncLocal<string?> _ambient = new();

    public static string? Current => _ambient.Value;

    public static string NewId() => Guid.NewGuid().ToString();

    /// <summary>True for 1..128 printable ASCII characters (0x21-0x7E), the same rule as the Go library.</summary>
    public static bool IsValid(string? id) =>
        id is { Length: > 0 and <= MaxLength } && id.All(c => c is >= '!' and <= '~');

    /// <summary>Sets the ambient request id until the returned scope is disposed; an empty id leaves the current one.</summary>
    public static IDisposable Use(string? requestId)
    {
        var previous = _ambient.Value;
        if (!string.IsNullOrEmpty(requestId))
        {
            _ambient.Value = requestId;
        }

        return new Scope(previous);
    }

    private sealed class Scope(string? previous) : IDisposable
    {
        public void Dispose() => _ambient.Value = previous;
    }
}

/// <summary>Logging scope carrying request_id (and user_id when known); the JSON formatter turns it into fields.</summary>
public sealed class RequestLogScope : IReadOnlyList<KeyValuePair<string, object?>>
{
    private readonly List<KeyValuePair<string, object?>> _items = [];

    public RequestLogScope(string? requestId, string? userId)
    {
        if (!string.IsNullOrEmpty(requestId))
        {
            _items.Add(new("request_id", requestId));
        }

        if (!string.IsNullOrEmpty(userId))
        {
            _items.Add(new("user_id", userId));
        }
    }

    public int Count => _items.Count;

    public KeyValuePair<string, object?> this[int index] => _items[index];

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator() => _items.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public override string ToString() => string.Join(' ', _items.Select(i => $"{i.Key}={i.Value}"));
}

/// <summary>Standard gRPC health service (grpc.health.v1): neither authenticated, logged nor counted.</summary>
public static class HealthMethods
{
    public const string Prefix = "/grpc.health.v1.Health/";

    public static bool IsHealth(string? method) => method is not null && method.StartsWith(Prefix, StringComparison.Ordinal);
}

/// <summary>
/// Outermost server interceptor: takes x-request-id from the call (a fresh id when absent or unusable), makes it
/// ambient and a log scope, counts and times the call (taakht_grpc_server_*) and writes one log line per call with
/// the method, status code and duration. Registered first, so it sees the final status after the overload and
/// domain-exception mapping.
/// </summary>
public sealed class GrpcObservabilityInterceptor(ILogger<GrpcObservabilityInterceptor> logger) : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
        TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(continuation);
        if (HealthMethods.IsHealth(context.Method))
        {
            return await continuation(request, context);
        }

        var id = context.RequestHeaders.GetValue(RequestContext.Header);
        if (!RequestContext.IsValid(id))
        {
            id = RequestContext.NewId();
        }

        var userId = context.RequestHeaders.GetValue(IdentityConstants.UserIdHeader);
        using var ambient = RequestContext.Use(id);
        using var scope = logger.BeginScope(new RequestLogScope(id, userId is not null && CurrentUser.IsValid(userId) ? userId : null));
        var start = Stopwatch.GetTimestamp();
        var code = StatusCode.OK;
        try
        {
            return await continuation(request, context);
        }
        catch (RpcException ex)
        {
            code = ex.StatusCode;
            throw;
        }
        catch (OperationCanceledException)
        {
            code = StatusCode.Cancelled;
            throw;
        }
        catch (Exception)
        {
            code = StatusCode.Unknown;
            throw;
        }
        finally
        {
            var elapsed = Stopwatch.GetElapsedTime(start);
            var codeName = PlatformMetrics.CodeName(code);
            var millis = Math.Round(elapsed.TotalMilliseconds, 3);
            PlatformMetrics.GrpcRequests.WithLabels(context.Method, codeName).Inc();
            PlatformMetrics.GrpcDuration.WithLabels(context.Method).Observe(elapsed.TotalSeconds);
            var level = LevelFor(code);
            if (logger.IsEnabled(level))
            {
                logger.Log(level, "grpc call {Method} {Code} {DurationMs}", context.Method, codeName, millis);
            }
        }
    }

    private static LogLevel LevelFor(StatusCode code) => code switch
    {
        StatusCode.OK => LogLevel.Information,
        StatusCode.Unknown or StatusCode.Internal or StatusCode.DataLoss or StatusCode.Unavailable or StatusCode.DeadlineExceeded => LogLevel.Error,
        _ => LogLevel.Warning, // the caller's mistake or an expected refusal
    };
}

/// <summary>Forwards the ambient request id as x-request-id on outgoing unary calls.</summary>
public sealed class ClientRequestIdInterceptor : Interceptor
{
    public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(
        TRequest request, ClientInterceptorContext<TRequest, TResponse> context,
        AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
        => continuation(request, WithRequestId(context));

    public override TResponse BlockingUnaryCall<TRequest, TResponse>(
        TRequest request, ClientInterceptorContext<TRequest, TResponse> context,
        BlockingUnaryCallContinuation<TRequest, TResponse> continuation)
        => continuation(request, WithRequestId(context));

    private static ClientInterceptorContext<TRequest, TResponse> WithRequestId<TRequest, TResponse>(
        ClientInterceptorContext<TRequest, TResponse> context)
        where TRequest : class
        where TResponse : class
    {
        var id = RequestContext.Current;
        if (string.IsNullOrEmpty(id))
        {
            return context;
        }

        var headers = context.Options.Headers ?? [];
        if (headers.GetValue(RequestContext.Header) is null)
        {
            headers.Add(RequestContext.Header, id);
        }

        return new ClientInterceptorContext<TRequest, TResponse>(
            context.Method, context.Host, context.Options.WithHeaders(headers));
    }
}
