<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Taakht.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="prometheus-net.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Taakht.Platform.Tests" />
    <Protobuf Include="../../../api/proto/taakht/common/v1/envelope.proto" ProtoRoot="../../../api/proto" GrpcServices="None" Link="Protos/envelope.proto" />
  </ItemGroup>

</Project>
