<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Taakht.Negotiation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../libs/dotnet/Taakht.Platform/Taakht.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../../third_party/google/api/annotations.proto" ProtoRoot="../../../third_party" GrpcServices="None" Link="Protos/google_api_annotations.proto" />
    <Protobuf Include="../../../third_party/google/api/http.proto" ProtoRoot="../../../third_party" GrpcServices="None" Link="Protos/google_api_http.proto" />
    <Protobuf Include="../../../api/proto/taakht/negotiation/v1/negotiation.proto" ProtoRoot="../../../api/proto" AdditionalImportDirs="../../../third_party" GrpcServices="Server" Link="Protos/negotiation.proto" />
    <Protobuf Include="../../../api/proto/taakht/negotiation/v1/events.proto" ProtoRoot="../../../api/proto" AdditionalImportDirs="../../../third_party" GrpcServices="None" Link="Protos/negotiation_events.proto" />
    <Protobuf Include="../../../api/proto/taakht/ad/v1/ad.proto" ProtoRoot="../../../api/proto" AdditionalImportDirs="../../../third_party" GrpcServices="Client" Link="Protos/ad.proto" />
    <Protobuf Include="../../../api/proto/taakht/ad/v1/events.proto" ProtoRoot="../../../api/proto" AdditionalImportDirs="../../../third_party" GrpcServices="None" Link="Protos/ad_events.proto" />
    <Protobuf Include="../../../api/proto/taakht/swap/v1/events.proto" ProtoRoot="../../../api/proto" AdditionalImportDirs="../../../third_party" GrpcServices="None" Link="Protos/swap_events.proto" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="migrations/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Taakht.Negotiation.Tests" />
  </ItemGroup>

</Project>
